// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'NeoEdge NG4500 Series',
      items: [
        { type: 'autogenerated', dirName: '1-neoedge-ng4500-series' },
      ],
    },
    {
      type: 'category',
      label: 'NeoEyes NE101 Series',
      items: [
        { type: 'autogenerated', dirName: '2-neoeyes-ne101-series' },
      ],
    },
    {
      type: 'category',
      label: 'NeoEyes NE301 Series',
      items: [
        { type: 'autogenerated', dirName: '5-neoeyes-ne301-series' },
      ],
    },
    {
      type: 'category',
      label: 'NeoEyes NE503 Series',
      items: [
        { type: 'autogenerated', dirName: '6-neoeyes-ne503-series' },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Dev Resources',
      items: [
        { type: 'autogenerated', dirName: '3-hardware-dev-resources' },
      ],
    },
    {
      type: 'category',
      label: 'NeoMind',
      items: [
        { type: 'autogenerated', dirName: '0-neomind' },
      ],
    },
    {
      type: 'category',
      label: 'AI Application',
      items: [
        { type: 'autogenerated', dirName: '4-ai-application' },
      ],
    },
    {
      type: 'category',
      label: "Release Note",
      items: [
        { type: 'autogenerated', dirName: '7-release-notes' },
      ],
    }
  ],
};

export default sidebars;
