const sidebars = {
  tutorialSidebar: [
    'index',
    { type: 'category', label: 'NeoEdge NG4500 Series', items: [{ type: 'autogenerated', dirName: '1-neoedge-ng4500-series' }] },
    { type: 'category', label: 'NeoEyes NE101 Series', items: [{ type: 'autogenerated', dirName: '2-neoeyes-ne101-series' }] },
    { type: 'category', label: 'NeoEyes NE301 Series', items: [{ type: 'autogenerated', dirName: '5-neoeyes-ne301-series' }] },
    { type: 'category', label: 'NeoEyes NE302 Series', items: [{ type: 'autogenerated', dirName: '8-neoeyes-ne302-series' }] },
    { type: 'category', label: 'NeoEyes NE503 Series', items: [{ type: 'autogenerated', dirName: '6-neoeyes-ne503-series' }] },
    { type: 'category', label: 'Hardware Dev Resources', items: [{ type: 'autogenerated', dirName: '3-hardware-dev-resources' }] },
    { type: 'category', label: 'NeoMind', items: [{ type: 'autogenerated', dirName: '0-neomind' }] },
    { type: 'category', label: 'AI Application', items: [{ type: 'autogenerated', dirName: '4-ai-application' }] },
    { type: 'category', label: 'Release Note', items: [{ type: 'autogenerated', dirName: '7-release-notes' }] },
  ],
};

export default sidebars;
