name: Deploy wiki

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy_to_github_pages:
    name: 🚀 Deploy to GitHub Pages
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 3. Install dependencies
        run: yarn install --frozen-lockfile

      - name: 4. Build website
        env:
          NODE_ENV: production
          DEPLOY_ENV: github-pages
          SITE_URL: https://harryhua-ai.github.io
          BASE_URL: /wiki-documents/
        run: yarn build

      - name: 5. Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: 6. Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
